openapi: 3.0.0
info:
  title: Fudo Challenge API
  description: API para el Fudo Challenge.
  version: 1.0.0
servers:
  - url: http://localhost:9292
paths:
  /:
    get:
      summary: Mensaje de bienvenida
      responses:
        '200':
          description: Un mensaje de bienvenida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "¡Bienvenido a la API de Rack!"
  /authenticate:
    post:
      summary: Autenticar un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "admin"
                password:
                  type: string
                  example: "password"
      responses:
        '200':
          description: Autenticación exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "un_token_jwt_seguro_iría_aquí"
        '400':
          description: JSON inválido
        '401':
          description: Credenciales inválidas
        '405':
          description: Método no permitido
  /products:
    post:
      summary: Crear un producto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Pizza"
                price:
                  type: number
                  example: 10.5
      responses:
        '202':
          description: Solicitud de creación de producto aceptada
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "La solicitud de creación del producto se aceptó y se está procesando."
                  product_id:
                    type: string
                    format: uuid
        '400':
          description: JSON inválido o parámetros faltantes
  /products/{id}:
    get:
      summary: Obtener un producto por ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  price:
                    type: number
        '404':
          description: Producto no encontrado
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 